# inspired by https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
name: Build & Push SwaggerEditor@next Docker image

on:
  workflow_run:
    workflows: ["Release SwaggerEditor@next"]
    types:
      - completed
    branches: [next]

jobs:

  build-push:
    if: github.event.workflow_run.conclusion == 'success'
    name: Build & Push SwaggerEditor@next Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
          ref: next

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          registry-url: https://npm.pkg.github.com/
          scope: "@swagger-api"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}

      - name: Build App artifacts
        run: npm run build:app

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_SB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SB_PASSWORD }}

      - name: Build docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          tags: swaggerapi/swagger-editor:next-v5
